if(APPLE)
    set(YUCHEN_REQUIRED_FRAMEWORKS Cocoa Metal MetalKit QuartzCore CoreText CoreFoundation)
    
    foreach(framework_name ${YUCHEN_REQUIRED_FRAMEWORKS})
        find_library(YUCHEN_${framework_name}_FRAMEWORK ${framework_name} REQUIRED)
        if(NOT YUCHEN_${framework_name}_FRAMEWORK)
            message(FATAL_ERROR "${framework_name} framework not found")
        endif()
        list(APPEND YUCHEN_FRAMEWORKS ${YUCHEN_${framework_name}_FRAMEWORK})
    endforeach()
endif()

function(yuchen_link_dependencies target_name)
    if(APPLE)
        target_link_libraries(${target_name} PUBLIC ${YUCHEN_FRAMEWORKS})
    elseif(WIN32)
        target_link_libraries(${target_name} PUBLIC ${YUCHEN_PLATFORM_LIBS})
    endif()
    yuchen_log("Linked dependencies to ${target_name}")
endfunction()